import { expect, test } from '@playwright/test';
import { PNG } from 'pngjs';

test('renders a nonblank WebGL city scene', async ({ page }, testInfo) => {
  await page.goto('/?testMode=fast');
  await page.waitForFunction(() => document.body.dataset.sceneReady === 'true');

  await expect(page.locator('body')).toHaveAttribute('data-scene-validation-status', 'passed');
  await expect(page.locator('body')).toHaveAttribute('data-scene-validation-issues', '0');
  await expect
    .poll(() =>
      page.evaluate(() => ({
        validationPassed: window.cityDiagnostics?.validation.passed,
        configValidationPassed: window.cityDiagnostics?.config.validation.passed,
        configSchemaVersion: window.cityDiagnostics?.config.schemaVersion,
        configQualityPreset: window.cityDiagnostics?.config.city.qualityPreset,
        configTrafficDensity: window.cityDiagnostics?.config.city.density.trafficDensity,
        configPropDensity: window.cityDiagnostics?.config.city.density.propDensity,
        renderQualityPreset: window.cityDiagnostics?.config.render.qualityPreset,
        masterPlanValidationPassed: window.cityDiagnostics?.masterPlan.validation.passed,
        masterPlanCenters: window.cityDiagnostics?.objectCounts.masterPlanCenters,
        masterPlanProtectedOpenSpaces: window.cityDiagnostics?.objectCounts.masterPlanProtectedOpenSpaces,
        masterPlanGrowthBoundaries: window.cityDiagnostics?.objectCounts.masterPlanGrowthBoundaries,
        masterPlanCityForm: window.cityDiagnostics?.masterPlan.cityFormKind,
        districtCharacterRules: window.cityDiagnostics?.districtCharacter.districtRules,
        districtUseMixRules: window.cityDiagnostics?.objectCounts.districtUseMixRules,
        districtLandmarkTargets: window.cityDiagnostics?.objectCounts.districtLandmarkTargets,
        districtTransitionBuffers: window.cityDiagnostics?.objectCounts.districtTransitionBuffers,
        districtStylePalettes: window.cityDiagnostics?.objectCounts.districtStylePalettes,
        cityMetrics: window.cityDiagnostics?.objectCounts.cityMetrics,
        cityMetricsPassing: window.cityDiagnostics?.cityMetrics.passing,
        cityMetricsWarnings: window.cityDiagnostics?.cityMetrics.warnings,
        cityMetricWalkability: window.cityDiagnostics?.cityMetrics.valuesByKind.walkability,
        cityMetricDensity: window.cityDiagnostics?.cityMetrics.valuesByKind.density,
        weatherPresets: window.cityDiagnostics?.objectCounts.weatherPresets,
        activeWeatherPresets: window.cityDiagnostics?.objectCounts.activeWeatherPresets,
        rainyWeatherPresets: window.cityDiagnostics?.objectCounts.rainyWeatherPresets,
        activeWeatherPresetId: window.cityDiagnostics?.climateWeather.activePresetId,
        activeWeatherPresetKind: window.cityDiagnostics?.climateWeather.activePresetKind,
        weatherOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'weather-presets')
          ?.featureCount,
        solarShadingSamples: window.cityDiagnostics?.objectCounts.solarShadingSamples,
        roofSolarSamples: window.cityDiagnostics?.objectCounts.roofSolarSamples,
        shadeComfortSamples: window.cityDiagnostics?.objectCounts.shadeComfortSamples,
        solarShadingHighGlareSamples: window.cityDiagnostics?.solarShading.highGlareSamples,
        solarShadingOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'solar-shading')
          ?.featureCount,
        urbanHeatZones: window.cityDiagnostics?.objectCounts.urbanHeatZones,
        urbanHeatHighRiskZones: window.cityDiagnostics?.objectCounts.urbanHeatHighRiskZones,
        urbanHeatPublicRouteRiskZones: window.cityDiagnostics?.objectCounts.urbanHeatPublicRouteRiskZones,
        urbanHeatOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'urban-heat')
          ?.featureCount,
        utilityNodes: window.cityDiagnostics?.objectCounts.utilityNodes,
        utilityEdges: window.cityDiagnostics?.objectCounts.utilityEdges,
        utilityNetworkTypes: window.cityDiagnostics?.objectCounts.utilityNetworkTypes,
        utilityServiceParcels: window.cityDiagnostics?.objectCounts.utilityServiceParcels,
        utilityCriticalObjects: window.cityDiagnostics?.objectCounts.utilityCriticalObjects,
        utilityBackupNodes: window.cityDiagnostics?.objectCounts.utilityBackupNodes,
        utilityHighCriticalityNodes: window.cityDiagnostics?.objectCounts.utilityHighCriticalityNodes,
        serviceAccessCorridors: window.cityDiagnostics?.objectCounts.serviceAccessCorridors,
        serviceAccessUtilityEasements: window.cityDiagnostics?.objectCounts.serviceAccessUtilityEasements,
        serviceAccessVaults: window.cityDiagnostics?.objectCounts.serviceAccessVaults,
        serviceAccessMaintenancePaths: window.cityDiagnostics?.objectCounts.serviceAccessMaintenancePaths,
        serviceAccessServiceYards: window.cityDiagnostics?.objectCounts.serviceAccessServiceYards,
        serviceAccessRestrictedCorridors: window.cityDiagnostics?.objectCounts.serviceAccessRestrictedCorridors,
        buildingsWithServiceAccess: window.cityDiagnostics?.objectCounts.buildingsWithServiceAccess,
        utilityNodesWithServiceAccess: window.cityDiagnostics?.objectCounts.utilityNodesWithServiceAccess,
        utilityEdgesWithServiceAccess: window.cityDiagnostics?.objectCounts.utilityEdgesWithServiceAccess,
        serviceAccessOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'service-access')
          ?.featureCount,
        buildingEntrances: window.cityDiagnostics?.objectCounts.buildingEntrances,
        publicBuildingEntrances: window.cityDiagnostics?.objectCounts.publicBuildingEntrances,
        lobbyEntrances: window.cityDiagnostics?.objectCounts.lobbyEntrances,
        rampEntrances: window.cityDiagnostics?.objectCounts.rampEntrances,
        serviceEntrances: window.cityDiagnostics?.objectCounts.serviceEntrances,
        loadingEntrances: window.cityDiagnostics?.objectCounts.loadingEntrances,
        addressPoints: window.cityDiagnostics?.objectCounts.addressPoints,
        formattedAddressPoints: window.cityDiagnostics?.objectCounts.formattedAddressPoints,
        namedPlaces: window.cityDiagnostics?.objectCounts.namedPlaces,
        namedNeighborhoodPlaces: window.cityDiagnostics?.objectCounts.namedNeighborhoodPlaces,
        namedStreetPlaces: window.cityDiagnostics?.objectCounts.namedStreetPlaces,
        gazetteerEntries: window.cityDiagnostics?.objectCounts.gazetteerEntries,
        addressGazetteerEntries: window.cityDiagnostics?.objectCounts.addressGazetteerEntries,
        anchorGazetteerEntries: window.cityDiagnostics?.objectCounts.anchorGazetteerEntries,
        reverseLookupEntries: window.cityDiagnostics?.objectCounts.reverseLookupEntries,
        civicAnchorsWithAddresses: window.cityDiagnostics?.objectCounts.civicAnchorsWithAddresses,
        addressingGazetteerOverlayFeatures: window.cityDiagnostics?.overlays.find(
          (overlay) => overlay.id === 'addressing-gazetteer'
        )?.featureCount,
        buildingsWithAddressPoints: window.cityDiagnostics?.objectCounts.buildingsWithAddressPoints,
        buildingsWithAccessiblePublicEntrances:
          window.cityDiagnostics?.objectCounts.buildingsWithAccessiblePublicEntrances,
        buildingAccessOverlayFeatures: window.cityDiagnostics?.overlays.find(
          (overlay) => overlay.id === 'building-access'
        )?.featureCount,
        accessControls: window.cityDiagnostics?.objectCounts.accessControls,
        accessControlGates: window.cityDiagnostics?.objectCounts.accessControlGates,
        accessControlCheckpoints: window.cityDiagnostics?.objectCounts.accessControlCheckpoints,
        accessControlTurnstiles: window.cityDiagnostics?.objectCounts.accessControlTurnstiles,
        publicAccessControls: window.cityDiagnostics?.objectCounts.publicAccessControls,
        privateAccessControls: window.cityDiagnostics?.objectCounts.privateAccessControls,
        accessControlledNavigationEdges: window.cityDiagnostics?.objectCounts.accessControlledNavigationEdges,
        accessControlOverlayFeatures: window.cityDiagnostics?.overlays.find(
          (overlay) => overlay.id === 'access-controls'
        )?.featureCount,
        powerGridNodes: window.cityDiagnostics?.objectCounts.powerGridNodes,
        powerGridEdges: window.cityDiagnostics?.objectCounts.powerGridEdges,
        powerTransformers: window.cityDiagnostics?.objectCounts.powerTransformers,
        powerMeters: window.cityDiagnostics?.objectCounts.powerMeters,
        powerStreetLightCircuits: window.cityDiagnostics?.objectCounts.powerStreetLightCircuits,
        buildingsWithPowerService: window.cityDiagnostics?.objectCounts.buildingsWithPowerService,
        streetLightsWithPowerCircuit: window.cityDiagnostics?.objectCounts.streetLightsWithPowerCircuit,
        waterSupplyNodes: window.cityDiagnostics?.objectCounts.waterSupplyNodes,
        waterSupplyEdges: window.cityDiagnostics?.objectCounts.waterSupplyEdges,
        waterHydrants: window.cityDiagnostics?.objectCounts.waterHydrants,
        waterValves: window.cityDiagnostics?.objectCounts.waterValves,
        waterPumps: window.cityDiagnostics?.objectCounts.waterPumps,
        waterTanks: window.cityDiagnostics?.objectCounts.waterTanks,
        buildingsWithWaterService: window.cityDiagnostics?.objectCounts.buildingsWithWaterService,
        wastewaterNodes: window.cityDiagnostics?.objectCounts.wastewaterNodes,
        wastewaterEdges: window.cityDiagnostics?.objectCounts.wastewaterEdges,
        wastewaterManholes: window.cityDiagnostics?.objectCounts.wastewaterManholes,
        wastewaterLiftStations: window.cityDiagnostics?.objectCounts.wastewaterLiftStations,
        wastewaterOutfalls: window.cityDiagnostics?.objectCounts.wastewaterOutfalls,
        buildingsWithWastewaterService: window.cityDiagnostics?.objectCounts.buildingsWithWastewaterService,
        stormwaterNodes: window.cityDiagnostics?.objectCounts.stormwaterNodes,
        stormwaterEdges: window.cityDiagnostics?.objectCounts.stormwaterEdges,
        stormwaterInlets: window.cityDiagnostics?.objectCounts.stormwaterInlets,
        stormwaterBioswales: window.cityDiagnostics?.objectCounts.stormwaterBioswales,
        stormwaterCulverts: window.cityDiagnostics?.objectCounts.stormwaterCulverts,
        roadsWithStormwaterDrainage: window.cityDiagnostics?.objectCounts.roadsWithStormwaterDrainage,
        telecomNodes: window.cityDiagnostics?.objectCounts.telecomNodes,
        telecomEdges: window.cityDiagnostics?.objectCounts.telecomEdges,
        telecomCellSites: window.cityDiagnostics?.objectCounts.telecomCellSites,
        telecomAntennas: window.cityDiagnostics?.objectCounts.telecomAntennas,
        buildingsWithTelecomService: window.cityDiagnostics?.objectCounts.buildingsWithTelecomService,
        gasDistrictEnergyNodes: window.cityDiagnostics?.objectCounts.gasDistrictEnergyNodes,
        gasNodes: window.cityDiagnostics?.objectCounts.gasNodes,
        districtEnergyNodes: window.cityDiagnostics?.objectCounts.districtEnergyNodes,
        gasDistrictEnergyEdges: window.cityDiagnostics?.objectCounts.gasDistrictEnergyEdges,
        buildingsWithThermalService: window.cityDiagnostics?.objectCounts.buildingsWithThermalService,
        developmentPhases: window.cityDiagnostics?.objectCounts.developmentPhases,
        activeDevelopmentPhases: window.cityDiagnostics?.objectCounts.activeDevelopmentPhases,
        temporaryRoadClosures: window.cityDiagnostics?.objectCounts.temporaryRoadClosures,
        temporaryPhaseAssets: window.cityDiagnostics?.objectCounts.temporaryPhaseAssets,
        phasingOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'phasing')
          ?.featureCount,
        waterwayEdgeSegments: window.cityDiagnostics?.objectCounts.waterwayEdgeSegments,
        waterwayChannels: window.cityDiagnostics?.objectCounts.waterwayChannels,
        waterwayCrossings: window.cityDiagnostics?.objectCounts.waterwayCrossings,
        waterwayCulverts: window.cityDiagnostics?.objectCounts.waterwayCulverts,
        waterwayDocks: window.cityDiagnostics?.objectCounts.waterwayDocks,
        waterwayOutfalls: window.cityDiagnostics?.objectCounts.waterwayOutfalls,
        waterwayContinuousEdges: window.cityDiagnostics?.waterwayNetwork.continuousEdgeWaterways,
        waterfrontEdges: window.cityDiagnostics?.objectCounts.waterfrontEdges,
        waterfrontPublicAccessEdges: window.cityDiagnostics?.objectCounts.waterfrontPublicAccessEdges,
        waterfrontFloodProtectionEdges: window.cityDiagnostics?.objectCounts.waterfrontFloodProtectionEdges,
        waterfrontPiers: window.cityDiagnostics?.objectCounts.waterfrontPiers,
        waterfrontModelTotal: window.cityDiagnostics?.waterfrontModel.total,
        waterfrontOpenSpaces: window.cityDiagnostics?.objectCounts.waterfrontOpenSpaces,
        waterfrontOpenSpaceSeating: window.cityDiagnostics?.objectCounts.waterfrontOpenSpaceSeating,
        waterfrontOpenSpaceRailings: window.cityDiagnostics?.objectCounts.waterfrontOpenSpaceRailings,
        waterfrontWaterAccessPoints: window.cityDiagnostics?.objectCounts.waterfrontWaterAccessPoints,
        waterfrontEcologicalOpenSpaces: window.cityDiagnostics?.objectCounts.waterfrontEcologicalOpenSpaces,
        waterfrontOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'waterfront')
          ?.featureCount,
        hazardZones: window.cityDiagnostics?.objectCounts.hazardZones,
        criticalHazards: window.cityDiagnostics?.objectCounts.criticalHazards,
        noBuildHazards: window.cityDiagnostics?.objectCounts.noBuildHazards,
        mitigationHazards: window.cityDiagnostics?.objectCounts.mitigationHazards,
        hazardOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'hazards')
          ?.featureCount,
        soilGeologyZones: window.cityDiagnostics?.objectCounts.soilGeologyZones,
        contaminatedSoilZones: window.cityDiagnostics?.objectCounts.contaminatedSoilZones,
        poorDrainageSoilZones: window.cityDiagnostics?.objectCounts.poorDrainageSoilZones,
        highRiskSoilZones: window.cityDiagnostics?.objectCounts.highRiskSoilZones,
        parcelsWithSoilGeology: window.cityDiagnostics?.objectCounts.parcelsWithSoilGeology,
        buildingsWithSoilGeology: window.cityDiagnostics?.objectCounts.buildingsWithSoilGeology,
        soilGeologyOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'soil-geology')
          ?.featureCount,
        administrativeBoundaries: window.cityDiagnostics?.objectCounts.administrativeBoundaries,
        wards: window.cityDiagnostics?.objectCounts.wards,
        neighborhoods: window.cityDiagnostics?.objectCounts.neighborhoods,
        constraints: window.cityDiagnostics?.objectCounts.constraints,
        resilienceGoals: window.cityDiagnostics?.objectCounts.resilienceGoals,
        resilienceCriticalGoals: window.cityDiagnostics?.resilienceGoals.criticalGoals,
        resilienceShelterCandidates: window.cityDiagnostics?.resilienceGoals.shelterCandidates,
        constraintNoBuildRules: window.cityDiagnostics?.constraintLayer.noBuildRules,
        validationIssuesWithFocus: window.cityDiagnostics?.validationIssueFocus.issuesWithFocus,
        validationIssuesWithSuggestedFix: window.cityDiagnostics?.validationIssueFocus.issuesWithSuggestedFix,
        trafficValidationPassed: window.cityDiagnostics?.trafficValidation.passed,
        sceneLayers: window.cityDiagnostics?.objectCounts.sceneLayers,
        sceneLayerIds: window.cityDiagnostics?.sceneLayers.map((layer) => layer.id).join(','),
        networkLayerObjects: window.cityDiagnostics?.sceneLayers.find((layer) => layer.id === 'networks')?.objectCount,
        agentLayerObjects: window.cityDiagnostics?.sceneLayers.find((layer) => layer.id === 'agents')?.objectCount,
        overlayDatasets: window.cityDiagnostics?.objectCounts.overlayDatasets,
        overlayFeatures: window.cityDiagnostics?.objectCounts.overlayFeatures,
        overlayIds: window.cityDiagnostics?.overlays.map((overlay) => overlay.id).join(','),
        validationOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'validation-issues')
          ?.featureCount,
        ownerDomainOverlayFeatures: window.cityDiagnostics?.overlays.find((overlay) => overlay.id === 'owner-domains')
          ?.featureCount,
        pickableObjects: window.cityDiagnostics?.objectCounts.pickableObjects,
        firstBuildingPickMetadataParcel: window.cityDiagnostics?.picking.pickableObjects.find(
          (metadata) => metadata.kind === 'building'
        )?.references.parcelId,
        roadPickMetadataLayer: window.cityDiagnostics?.picking.metadataByObjectId['road-v-0']?.ownerDomain,
        performanceBaselineStatus: window.cityDiagnostics?.performance.budget.status,
        performanceBaselineAgents: window.cityDiagnostics?.performance.agents.active,
        runtimeLayerNames: (
          window.cityApp as unknown as { city?: { group: { children: { name: string }[] } } }
        ).city?.group.children.map((child) => child.name).join(','),
        roads: window.cityDiagnostics?.objectCounts.roads,
        verticalSlices: window.cityDiagnostics?.objectCounts.verticalSlices,
        detailedStreetSliceId: window.cityDiagnostics?.objectIndex.objectsById['slice-detailed-street-road-v-6']?.id,
        detailedStreetSliceRoad: (
          window.cityDiagnostics?.objectIndex.objectsById['slice-detailed-street-road-v-6'] as
            | { corridorRoadId?: string }
            | undefined
        )?.corridorRoadId,
        intersections: window.cityDiagnostics?.objectCounts.intersections,
        crossings: window.cityDiagnostics?.objectCounts.crossings,
        midblockCrossings: window.cityDiagnostics?.objectCounts.midblockCrossings,
        raisedCrossings: window.cityDiagnostics?.objectCounts.raisedCrossings,
        tactileCrossings: window.cityDiagnostics?.objectCounts.tactileCrossings,
        crossingRefugeIslands: window.cityDiagnostics?.objectCounts.crossingRefugeIslands,
        crossingSignalPhases: window.cityDiagnostics?.objectCounts.crossingSignalPhases,
        continentalCrossings: window.cityDiagnostics?.crossingDetails.byType.continental,
        raisedTableCrossings: window.cityDiagnostics?.crossingDetails.byType['raised-table'],
        pedestrianPriorityCrossings: window.cityDiagnostics?.crossingDetails.byPriority['pedestrian-priority'],
        accessibleSidewalks: window.cityDiagnostics?.sidewalkAccessibility.accessibleSidewalks,
        accessibleGraphNodes: window.cityDiagnostics?.sidewalkAccessibility.accessibleGraphNodes,
        accessibleGraphEdges: window.cityDiagnostics?.sidewalkAccessibility.accessibleGraphEdges,
        curbRampAnchors: window.cityDiagnostics?.sidewalkAccessibility.curbRampAnchors,
        tactileCueAnchors: window.cityDiagnostics?.sidewalkAccessibility.tactileCueAnchors,
        minimumClearPathMeters: window.cityDiagnostics?.sidewalkAccessibility.minimumClearPathMeters,
        maximumRunningGradePercent: window.cityDiagnostics?.sidewalkAccessibility.maximumRunningGradePercent,
        curbZones: window.cityDiagnostics?.objectCounts.curbZones,
        trafficCalmingDevices: window.cityDiagnostics?.objectCounts.trafficCalmingDevices,
        curbExtensions: window.cityDiagnostics?.objectCounts.curbExtensions,
        busBulbs: window.cityDiagnostics?.objectCounts.busBulbs,
        speedTables: window.cityDiagnostics?.objectCounts.speedTables,
        trafficCalmingMinimumSpeed: window.cityDiagnostics?.trafficCalming.minimumTargetSpeedKph,
        sidewalkGraphNodes: window.cityDiagnostics?.objectCounts.sidewalkGraphNodes,
        sidewalkGraphEdges: window.cityDiagnostics?.objectCounts.sidewalkGraphEdges,
        buildings: window.cityDiagnostics?.objectCounts.buildings,
        civicAnchors: window.cityDiagnostics?.objectCounts.civicAnchors,
        civicAnchorServiceTypes: window.cityDiagnostics?.objectCounts.civicAnchorServiceTypes,
        civicAnchorDailyVisitors: window.cityDiagnostics?.objectCounts.civicAnchorDailyVisitors,
        civicAnchorEmergencyAccess: window.cityDiagnostics?.objectCounts.civicAnchorEmergencyAccess,
        communityAnchors: window.cityDiagnostics?.objectCounts.communityAnchors,
        communityAnchorKinds: window.cityDiagnostics?.objectCounts.communityAnchorKinds,
        communityDailyVisitors: window.cityDiagnostics?.objectCounts.communityDailyVisitors,
        communityEventCapacity: window.cityDiagnostics?.objectCounts.communityEventCapacity,
        communitySocialServiceCapacity: window.cityDiagnostics?.objectCounts.communitySocialServiceCapacity,
        communityShelterCapacity: window.cityDiagnostics?.objectCounts.communityShelterCapacity,
        communityCoverageScore: window.cityDiagnostics?.objectCounts.communityCoverageScore,
        communityCrowdReadyAnchors: window.cityDiagnostics?.objectCounts.communityCrowdReadyAnchors,
        communityFoodDistributionAnchors: window.cityDiagnostics?.objectCounts.communityFoodDistributionAnchors,
        cultureAnchors: window.cityDiagnostics?.objectCounts.cultureAnchors,
        cultureAnchorKinds: window.cityDiagnostics?.objectCounts.cultureAnchorKinds,
        cultureFootfallDaily: window.cityDiagnostics?.objectCounts.cultureFootfallDaily,
        cultureEventCapacity: window.cityDiagnostics?.objectCounts.cultureEventCapacity,
        cultureTourismScore: window.cityDiagnostics?.objectCounts.cultureTourismScore,
        cultureEveningAnchors: window.cityDiagnostics?.objectCounts.cultureEveningAnchors,
        cultureHeritageAnchors: window.cityDiagnostics?.objectCounts.cultureHeritageAnchors,
        governmentAnchors: window.cityDiagnostics?.objectCounts.governmentAnchors,
        governmentAnchorKinds: window.cityDiagnostics?.objectCounts.governmentAnchorKinds,
        governmentServiceCounters: window.cityDiagnostics?.objectCounts.governmentServiceCounters,
        governmentDailyVisitors: window.cityDiagnostics?.objectCounts.governmentDailyVisitors,
        governmentStaffCapacity: window.cityDiagnostics?.objectCounts.governmentStaffCapacity,
        governmentPlazaLinks: window.cityDiagnostics?.objectCounts.governmentPlazaLinks,
        activeFrontages: window.cityDiagnostics?.objectCounts.activeFrontages,
        trees: window.cityDiagnostics?.objectCounts.trees,
        parkTrees: window.cityDiagnostics?.objectCounts.parkTrees,
        streetTrees: window.cityDiagnostics?.objectCounts.streetTrees,
        planterTrees: window.cityDiagnostics?.objectCounts.planterTrees,
        greenCorridors: window.cityDiagnostics?.objectCounts.greenCorridors,
        treeCanopyAreaSquareMeters: window.cityDiagnostics?.objectCounts.treeCanopyAreaSquareMeters,
        treeSoilVolumeCubicMeters: window.cityDiagnostics?.objectCounts.treeSoilVolumeCubicMeters,
        plantingTotalTrees: window.cityDiagnostics?.plantingModel.totalTrees,
        plantingGreenCorridors: window.cityDiagnostics?.plantingModel.greenCorridors,
        plantingAverageHeatScore: window.cityDiagnostics?.plantingModel.averageHeatMitigationScore,
        plantingAverageEcologyScore: window.cityDiagnostics?.plantingModel.averageEcologyScore,
        streetLights: window.cityDiagnostics?.objectCounts.streetLights,
        streetFurniture: window.cityDiagnostics?.objectCounts.streetFurniture,
        detailedStreetFurniture: window.cityDiagnostics?.objectCounts.detailedStreetFurniture,
        citywideStreetFurniture: window.cityDiagnostics?.objectCounts.citywideStreetFurniture,
        railings: window.cityDiagnostics?.objectCounts.railings,
        transitShelters: window.cityDiagnostics?.objectCounts.transitShelters,
        parkFeatures: window.cityDiagnostics?.objectCounts.parkFeatures,
        parkPaths: window.cityDiagnostics?.objectCounts.parkPaths,
        parkProgramZones: window.cityDiagnostics?.objectCounts.parkProgramZones,
        parkSidewalkConnections: window.cityDiagnostics?.objectCounts.parkSidewalkConnections,
        parkExpansionFeatures: window.cityDiagnostics?.parkExpansion.totalFeatures,
        parkExpansionConnectedParks: window.cityDiagnostics?.parkExpansion.connectedParks,
        plazaZones: window.cityDiagnostics?.objectCounts.plazaZones,
        plazaEventCapacity: window.cityDiagnostics?.objectCounts.plazaEventCapacity,
        plazaActiveEdges: window.cityDiagnostics?.objectCounts.plazaActiveEdges,
        plazaLinkedFrontages: window.cityDiagnostics?.objectCounts.plazaLinkedFrontages,
        plazaModelZones: window.cityDiagnostics?.plazaModel.totalZones,
        plazaModelEventCapacity: window.cityDiagnostics?.plazaModel.eventCapacityPeople,
        assetDefinitions: window.cityDiagnostics?.objectCounts.assetDefinitions,
        renderBindings: window.cityDiagnostics?.objectCounts.renderBindings,
        bindingsWithAssets: window.cityDiagnostics?.assetBindingDiagnostics.bindingsWithAssets,
        bindingsMissingAssets: window.cityDiagnostics?.assetBindingDiagnostics.bindingsMissingAssets,
        bindingsWithFallbacks: window.cityDiagnostics?.assetBindingDiagnostics.bindingsWithFallbacks,
        bindingsMissingFallbacks: window.cityDiagnostics?.assetBindingDiagnostics.bindingsMissingFallbacks,
        unboundAssetDefinitions: window.cityDiagnostics?.assetBindingDiagnostics.unboundAssetDefinitions,
        importExportFormats: window.cityDiagnostics?.importExport.supportedFormatCount,
        importExportProceduralObjects: window.cityDiagnostics?.importExport.proceduralSeedExport.objectCount,
        importExportJsonSerializable: window.cityDiagnostics?.importExport.proceduralSeedExport.jsonSerializable,
        importExportRendererOnlyFields:
          window.cityDiagnostics?.importExport.proceduralSeedExport.rendererOnlyFieldCount,
        objectGroups: window.cityDiagnostics?.objectCounts.objectGroups,
        emptyObjectGroups: window.cityDiagnostics?.objectCounts.emptyObjectGroups,
        objectGroupValidationPassed: window.cityDiagnostics?.objectGroups.validation.passed,
        objectGroupMissingReferences: window.cityDiagnostics?.objectGroups.missingObjectReferences,
        ownerDomainGroups: window.cityDiagnostics?.objectGroups.countsByKind['owner-domain'],
        renderLayerGroups: window.cityDiagnostics?.objectGroups.countsByKind['render-layer'],
        networkRenderLayerObjects:
          window.cityDiagnostics?.objectGroupIndex.groupsById['group:render-layer:networks']?.objectCount,
        baselineScenarioObjects:
          window.cityDiagnostics?.objectGroupIndex.groupsById['group:scenario-layer:baseline']?.objectCount,
        registeredObjectKinds: window.cityDiagnostics?.objectCounts.registeredObjectKinds,
        registryKinds: window.cityDiagnostics?.objectRegistry.registeredKinds,
        geospatialUnit: window.cityDiagnostics?.geospatial.unit,
        geospatialCoordinateSystem: window.cityDiagnostics?.geospatial.coordinateSystem,
        geospatialOriginId: window.cityDiagnostics?.geospatial.originMetadata.id,
        geospatialPrecision: window.cityDiagnostics?.geospatial.precision.coordinatePrecisionMeters,
        heightDatum: window.cityDiagnostics?.geospatial.heightDatum.id,
        importProjectionStatus: window.cityDiagnostics?.geospatial.importProjection.status,
        metadataTaggedObjects: window.cityDiagnostics?.sourceMetadata.objectsWithMetadata,
        metadataMissingObjects: window.cityDiagnostics?.sourceMetadata.objectsMissingMetadata,
        metadataProceduralObjects: window.cityDiagnostics?.sourceMetadata.sourceTypes.procedural,
        metadataSimulatedObjects: window.cityDiagnostics?.sourceMetadata.sourceTypes.simulated,
        lodPolicyTiers: window.cityDiagnostics?.lodCoverage.tierCount,
        lodObjectPolicies: window.cityDiagnostics?.lodCoverage.objectPolicyCount,
        lodObjectsWithPolicy: window.cityDiagnostics?.lodCoverage.objectsWithPolicy,
        lodObjectsWithoutPolicy: window.cityDiagnostics?.lodCoverage.objectsWithoutPolicy,
        lodUnsupportedObjects: window.cityDiagnostics?.lodCoverage.objectsWithUnsupportedTier,
        trafficVehicles: window.cityDiagnostics?.objectCounts.trafficVehicles,
        duplicateObjectIds: window.cityDiagnostics?.objectCounts.duplicateObjectIds,
        lanes: window.cityDiagnostics?.objectCounts.lanes,
        sidewalks: window.cityDiagnostics?.objectCounts.sidewalks,
        laneMarkings: window.cityDiagnostics?.objectCounts.laneMarkings,
        firstIntersectionRoads: (
          window.cityDiagnostics?.objectIndex.objectsById['intersection-v0-h0'] as
            | { connectedRoadIds?: readonly string[] }
            | undefined
        )?.connectedRoadIds?.join(','),
        firstCrossingSidewalks: (
          window.cityDiagnostics?.objectIndex.objectsById['crossing-intersection-v0-h0-road-v-0'] as
            | { connectedSidewalkIds?: readonly string[] }
            | undefined
        )?.connectedSidewalkIds?.join(','),
        roadLaneParent: window.cityDiagnostics?.objectIndex.objectsById['road-v-0-lane-0']?.parentId,
        trafficVehicleKind: window.cityDiagnostics?.objectIndex.objectsById['traffic-vehicle-0']?.kind,
        trafficVehicleLane: (
          window.cityDiagnostics?.objectIndex.objectsById['traffic-vehicle-0'] as
            | { laneId?: string }
            | undefined
        )?.laneId,
        trafficVehicleRouteNodes: (
          window.cityDiagnostics?.objectIndex.objectsById['traffic-vehicle-0'] as
            | { route?: { nodeIds?: readonly string[] } }
            | undefined
        )?.route?.nodeIds?.length,
        vehicleFallbackGeometry: window.cityDiagnostics?.assetBindings.find(
          (binding) => binding.id === 'binding:vehicle:traffic-car'
        )?.fallbackGeometry,
        storefrontFallbackGeometry: window.cityDiagnostics?.assetBindings.find(
          (binding) => binding.id === 'binding:facade:storefront-window'
        )?.fallbackGeometry,
        trafficVehicleParentResolves: Boolean(
          window.cityDiagnostics?.objectIndex.objectsById[
            window.cityDiagnostics.objectIndex.objectsById['traffic-vehicle-0']?.parentId ?? ''
          ]
        )
      }))
    )
    .toEqual({
      validationPassed: true,
      configValidationPassed: true,
      configSchemaVersion: 'city-config-schema-v1',
      configQualityPreset: 'medium',
      configTrafficDensity: 0.42,
      configPropDensity: 0.68,
      renderQualityPreset: 'medium',
      masterPlanValidationPassed: true,
      masterPlanCenters: 4,
      masterPlanProtectedOpenSpaces: 3,
      masterPlanGrowthBoundaries: 3,
      masterPlanCityForm: 'river-coastal-polycentric-grid',
      districtCharacterRules: 5,
      districtUseMixRules: 17,
      districtLandmarkTargets: 5,
      districtTransitionBuffers: 14,
      districtStylePalettes: 5,
      cityMetrics: 8,
      cityMetricsPassing: 6,
      cityMetricsWarnings: 2,
      cityMetricWalkability: 96.02,
      cityMetricDensity: 2029.27,
      weatherPresets: 5,
      activeWeatherPresets: 1,
      rainyWeatherPresets: 3,
      activeWeatherPresetId: 'weather-preset-coastal-clear',
      activeWeatherPresetKind: 'clear',
      weatherOverlayFeatures: 5,
      solarShadingSamples: 24,
      roofSolarSamples: 12,
      shadeComfortSamples: 12,
      solarShadingHighGlareSamples: 3,
      solarShadingOverlayFeatures: 24,
      urbanHeatZones: 17,
      urbanHeatHighRiskZones: 2,
      urbanHeatPublicRouteRiskZones: 2,
      urbanHeatOverlayFeatures: 17,
      utilityNodes: 45,
      utilityEdges: 38,
      utilityNetworkTypes: 8,
      utilityServiceParcels: 72,
      utilityCriticalObjects: 135,
      utilityBackupNodes: 30,
      utilityHighCriticalityNodes: 25,
      serviceAccessCorridors: 744,
      serviceAccessUtilityEasements: 583,
      serviceAccessVaults: 45,
      serviceAccessMaintenancePaths: 38,
      serviceAccessServiceYards: 74,
      serviceAccessRestrictedCorridors: 4,
      buildingsWithServiceAccess: 583,
      utilityNodesWithServiceAccess: 45,
      utilityEdgesWithServiceAccess: 38,
      serviceAccessOverlayFeatures: 744,
      buildingEntrances: 2770,
      publicBuildingEntrances: 583,
      lobbyEntrances: 583,
      rampEntrances: 583,
      serviceEntrances: 583,
      loadingEntrances: 438,
      addressPoints: 583,
      formattedAddressPoints: 583,
      namedPlaces: 57,
      namedNeighborhoodPlaces: 5,
      namedStreetPlaces: 26,
      gazetteerEntries: 665,
      addressGazetteerEntries: 583,
      anchorGazetteerEntries: 25,
      reverseLookupEntries: 665,
      civicAnchorsWithAddresses: 6,
      addressingGazetteerOverlayFeatures: 722,
      buildingsWithAddressPoints: 583,
      buildingsWithAccessiblePublicEntrances: 583,
      buildingAccessOverlayFeatures: 3353,
      accessControls: 12,
      accessControlGates: 2,
      accessControlCheckpoints: 2,
      accessControlTurnstiles: 3,
      publicAccessControls: 6,
      privateAccessControls: 5,
      accessControlledNavigationEdges: 18,
      accessControlOverlayFeatures: 12,
      powerGridNodes: 8,
      powerGridEdges: 7,
      powerTransformers: 3,
      powerMeters: 1,
      powerStreetLightCircuits: 1,
      buildingsWithPowerService: 583,
      streetLightsWithPowerCircuit: 12,
      waterSupplyNodes: 7,
      waterSupplyEdges: 6,
      waterHydrants: 2,
      waterValves: 1,
      waterPumps: 1,
      waterTanks: 1,
      buildingsWithWaterService: 583,
      wastewaterNodes: 6,
      wastewaterEdges: 5,
      wastewaterManholes: 2,
      wastewaterLiftStations: 1,
      wastewaterOutfalls: 1,
      buildingsWithWastewaterService: 583,
      stormwaterNodes: 8,
      stormwaterEdges: 7,
      stormwaterInlets: 2,
      stormwaterBioswales: 1,
      stormwaterCulverts: 1,
      roadsWithStormwaterDrainage: 26,
      telecomNodes: 7,
      telecomEdges: 6,
      telecomCellSites: 1,
      telecomAntennas: 2,
      buildingsWithTelecomService: 583,
      gasDistrictEnergyNodes: 8,
      gasNodes: 3,
      districtEnergyNodes: 5,
      gasDistrictEnergyEdges: 7,
      buildingsWithThermalService: 583,
      developmentPhases: 3,
      activeDevelopmentPhases: 1,
      temporaryRoadClosures: 3,
      temporaryPhaseAssets: 2,
      phasingOverlayFeatures: 3,
      waterwayEdgeSegments: 8,
      waterwayChannels: 3,
      waterwayCrossings: 13,
      waterwayCulverts: 8,
      waterwayDocks: 3,
      waterwayOutfalls: 4,
      waterwayContinuousEdges: 1,
      waterfrontEdges: 11,
      waterfrontPublicAccessEdges: 6,
      waterfrontFloodProtectionEdges: 4,
      waterfrontPiers: 3,
      waterfrontModelTotal: 11,
      waterfrontOpenSpaces: 8,
      waterfrontOpenSpaceSeating: 154,
      waterfrontOpenSpaceRailings: 543,
      waterfrontWaterAccessPoints: 3,
      waterfrontEcologicalOpenSpaces: 2,
      waterfrontOverlayFeatures: 19,
      hazardZones: 6,
      criticalHazards: 1,
      noBuildHazards: 2,
      mitigationHazards: 6,
      hazardOverlayFeatures: 6,
      soilGeologyZones: 5,
      contaminatedSoilZones: 3,
      poorDrainageSoilZones: 2,
      highRiskSoilZones: 2,
      parcelsWithSoilGeology: 583,
      buildingsWithSoilGeology: 583,
      soilGeologyOverlayFeatures: 5,
      administrativeBoundaries: 18,
      wards: 4,
      neighborhoods: 5,
      constraints: 11,
      resilienceGoals: 7,
      resilienceCriticalGoals: 3,
      resilienceShelterCandidates: 3,
      constraintNoBuildRules: 3,
      validationIssuesWithFocus: 0,
      validationIssuesWithSuggestedFix: 0,
      trafficValidationPassed: true,
      sceneLayers: 6,
      sceneLayerIds: 'terrain,networks,buildings,public-realm,agents,overlays',
      networkLayerObjects: 4945,
      agentLayerObjects: 7,
      overlayDatasets: 32,
      overlayFeatures: 23777,
      overlayIds: 'administrative-boundaries,districts,zoning,waterways,waterfront,hazards,topography,soil-geology,phasing,weather-presets,solar-shading,urban-heat,city-metrics,cycling-network,navigation-graphs,freight-logistics,civic-anchors,community-anchors,culture-anchors,government-anchors,building-access,addressing-gazetteer,access-controls,constraints,resilience-goals,service-access,thermal-service,thermal-outages,parcels,roads,validation-issues,owner-domains',
      validationOverlayFeatures: 0,
      ownerDomainOverlayFeatures: 16105,
      pickableObjects: 6238,
      firstBuildingPickMetadataParcel: expect.stringMatching(/^parcel-/),
      roadPickMetadataLayer: 'mobility',
      performanceBaselineStatus: 'pass',
      performanceBaselineAgents: 7,
      runtimeLayerNames:
        'SceneLayer:terrain,SceneLayer:networks,SceneLayer:buildings,SceneLayer:public-realm,SceneLayer:agents,SceneLayer:overlays',
      roads: 26,
      verticalSlices: 1,
      detailedStreetSliceId: 'slice-detailed-street-road-v-6',
      detailedStreetSliceRoad: 'road-v-6',
      intersections: 169,
      crossings: 340,
      midblockCrossings: 2,
      raisedCrossings: 106,
      tactileCrossings: 340,
      crossingRefugeIslands: 130,
      crossingSignalPhases: 210,
      continentalCrossings: 130,
      raisedTableCrossings: 106,
      pedestrianPriorityCrossings: 18,
      accessibleSidewalks: 52,
      accessibleGraphNodes: 680,
      accessibleGraphEdges: 964,
      curbRampAnchors: 680,
      tactileCueAnchors: 680,
      minimumClearPathMeters: 1.8,
      maximumRunningGradePercent: 4.2,
      curbZones: 1300,
      trafficCalmingDevices: 12,
      curbExtensions: 2,
      busBulbs: 2,
      speedTables: 2,
      trafficCalmingMinimumSpeed: 15,
      sidewalkGraphNodes: 680,
      sidewalkGraphEdges: 964,
      buildings: 583,
      civicAnchors: 6,
      civicAnchorServiceTypes: 6,
      civicAnchorDailyVisitors: 3160,
      civicAnchorEmergencyAccess: 3,
      communityAnchors: 8,
      communityAnchorKinds: 8,
      communityDailyVisitors: 1700,
      communityEventCapacity: 1490,
      communitySocialServiceCapacity: 670,
      communityShelterCapacity: 140,
      communityCoverageScore: 652,
      communityCrowdReadyAnchors: 5,
      communityFoodDistributionAnchors: 1,
      cultureAnchors: 6,
      cultureAnchorKinds: 6,
      cultureFootfallDaily: 1680,
      cultureEventCapacity: 1260,
      cultureTourismScore: 505,
      cultureEveningAnchors: 4,
      cultureHeritageAnchors: 2,
      governmentAnchors: 5,
      governmentAnchorKinds: 5,
      governmentServiceCounters: 29,
      governmentDailyVisitors: 1400,
      governmentStaffCapacity: 430,
      governmentPlazaLinks: 5,
      activeFrontages: 44,
      trees: 145,
      parkTrees: 29,
      streetTrees: 116,
      planterTrees: 46,
      greenCorridors: 27,
      treeCanopyAreaSquareMeters: 3116,
      treeSoilVolumeCubicMeters: 1667,
      plantingTotalTrees: 145,
      plantingGreenCorridors: 27,
      plantingAverageHeatScore: 0.74,
      plantingAverageEcologyScore: 0.68,
      streetLights: 12,
      streetFurniture: 266,
      detailedStreetFurniture: 58,
      citywideStreetFurniture: 208,
      railings: 6,
      transitShelters: 19,
      parkFeatures: 24,
      parkPaths: 6,
      parkProgramZones: 18,
      parkSidewalkConnections: 6,
      parkExpansionFeatures: 24,
      parkExpansionConnectedParks: 3,
      plazaZones: 6,
      plazaEventCapacity: 255,
      plazaActiveEdges: 1,
      plazaLinkedFrontages: 4,
      plazaModelZones: 6,
      plazaModelEventCapacity: 255,
      assetDefinitions: 48,
      renderBindings: 48,
      bindingsWithAssets: 48,
      bindingsMissingAssets: 0,
      bindingsWithFallbacks: 48,
      bindingsMissingFallbacks: 0,
      unboundAssetDefinitions: 0,
      importExportFormats: 6,
      importExportProceduralObjects: 15148,
      importExportJsonSerializable: true,
      importExportRendererOnlyFields: 0,
      objectGroups: 32,
      emptyObjectGroups: 5,
      objectGroupValidationPassed: true,
      objectGroupMissingReferences: 0,
      ownerDomainGroups: 13,
      renderLayerGroups: 6,
      networkRenderLayerObjects: 4933,
      baselineScenarioObjects: 16105,
      registeredObjectKinds: 68,
      registryKinds: 68,
      geospatialUnit: 'meter',
      geospatialCoordinateSystem: 'local-xz',
      geospatialOriginId: 'local-origin-detailed-city-v1',
      geospatialPrecision: 0.01,
      heightDatum: 'local-ground-plane',
      importProjectionStatus: 'not-configured',
      metadataTaggedObjects: 16105,
      metadataMissingObjects: 0,
      metadataProceduralObjects: 16098,
      metadataSimulatedObjects: 7,
      lodPolicyTiers: 5,
      lodObjectPolicies: 68,
      lodObjectsWithPolicy: 16105,
      lodObjectsWithoutPolicy: 0,
      lodUnsupportedObjects: 0,
      trafficVehicles: 7,
      duplicateObjectIds: 0,
      lanes: 72,
      sidewalks: 52,
      laneMarkings: 950,
      firstIntersectionRoads: 'road-v-0,road-h-0',
      firstCrossingSidewalks: 'road-v-0-sidewalk-left,road-v-0-sidewalk-right',
      roadLaneParent: 'road-v-0',
      trafficVehicleKind: 'traffic-vehicle',
      trafficVehicleLane: 'road-v-0-lane-1',
      trafficVehicleRouteNodes: 13,
      vehicleFallbackGeometry: 'vehicle-box',
      storefrontFallbackGeometry: 'storefront-window-box',
      trafficVehicleParentResolves: true
    });

  const canvas = page.locator('canvas');
  await expect(canvas).toBeVisible();

  const screenshot = await page.screenshot({ fullPage: false });
  const png = PNG.sync.read(screenshot);
  let variedPixels = 0;

  for (let y = 0; y < png.height; y += 4) {
    for (let x = 0; x < png.width; x += 4) {
      const offset = (png.width * y + x) * 4;
      const red = png.data[offset];
      const green = png.data[offset + 1];
      const blue = png.data[offset + 2];
      const alpha = png.data[offset + 3];
      const brightness = red + green + blue;
      const channelSpread = Math.max(red, green, blue) - Math.min(red, green, blue);

      if (alpha > 0 && brightness > 45 && channelSpread > 5) {
        variedPixels += 1;
      }
    }
  }

  expect(variedPixels, `${testInfo.project.name} should render visible nonbackground pixels`).toBeGreaterThan(800);
});
