import { expect, test } from '@playwright/test';
import { createGeneratedCityObjectIndex } from '../../src/city/data-contracts/generatedCityObjectIndex';
import { validateGeneratedCity } from '../../src/city/data-contracts/validation/validateGeneratedCity';
import { validateTrafficPlan } from '../../src/city/data-contracts/validation/validateTrafficPlan';
import { createCityDiagnostics } from '../../src/app/cityDiagnostics';
import { cityConfig } from '../../src/config/cityConfig';
import { renderConfig } from '../../src/config/renderConfig';
import { CityGenerator } from '../../src/generation/CityGenerator';
import { TrafficLaneGenerator } from '../../src/generation/traffic/TrafficLaneGenerator';

test('generated city objects carry deterministic source metadata', () => {
  const firstCity = new CityGenerator(cityConfig).generate();
  const secondCity = new CityGenerator(cityConfig).generate();

  expect(firstCity.objectIndex.objects.map((object) => object.metadata?.sourceId)).toEqual(
    secondCity.objectIndex.objects.map((object) => object.metadata?.sourceId)
  );
  expect(firstCity.objectIndex.objects.every((object) => object.metadata)).toBe(true);
  expect(firstCity.validation.issues.filter((issue) => issue.category === 'metadata')).toEqual([]);
  expect(firstCity.roads[0].metadata).toMatchObject({
    sourceType: 'procedural',
    sourceId: 'generated:mobility-road-network:road-v-0',
    generationStep: 'mobility-road-network',
    reviewStatus: 'generated',
    license: 'internal-procedural'
  });
  expect(firstCity.roads[0].lanes[0].metadata).toMatchObject({
    sourceType: 'procedural',
    sourceId: 'generated:mobility-road-lanes:road-v-0-lane-0',
    generationStep: 'mobility-road-lanes'
  });
  expect(firstCity.assetCatalog[0]).toMatchObject({
    license: 'internal-procedural',
    attribution: 'Procedural fallback primitive generated by detailed-city.',
    metadata: {
      sourceType: 'procedural',
      generationStep: 'render-asset-catalog',
      reviewStatus: 'generated',
      license: 'internal-procedural'
    }
  });
});

test('runtime traffic source metadata is validated and exposed in diagnostics', () => {
  const city = new CityGenerator(cityConfig).generate();
  const traffic = createTraffic(city);
  const diagnostics = createCityDiagnostics(city, traffic, renderConfig);

  expect(validateTraffic(city, traffic).issues.filter((issue) => issue.category === 'metadata')).toEqual([]);
  expect(traffic.markings.every((marking) => marking.metadata?.sourceType === 'procedural')).toBe(true);
  expect(traffic.vehicles.every((vehicle) => vehicle.metadata?.sourceType === 'simulated')).toBe(true);
  expect(diagnostics.sourceMetadata).toEqual({
    objectsWithMetadata: 4764,
    objectsMissingMetadata: 0,
    objectsRequiringReview: 0,
    sourceTypes: {
      procedural: 4757,
      authored: 0,
      imported: 0,
      simulated: 7
    }
  });
});

test('metadata validation warns for missing generated and asset provenance', () => {
  const city = new CityGenerator(cityConfig).generate();
  const [road, ...remainingRoads] = city.roads;
  const [asset, ...remainingAssets] = city.assetCatalog;
  const invalidCity = {
    ...city,
    roads: [
      {
        ...road,
        metadata: undefined
      },
      ...remainingRoads
    ],
    assetCatalog: [
      {
        ...asset,
        attribution: undefined,
        license: undefined
      },
      ...remainingAssets
    ]
  };
  const validation = validateGeneratedCity({
    ...invalidCity,
    objectIndex: createGeneratedCityObjectIndex(invalidCity)
  });

  expect(validation.passed).toBe(true);
  expect(validation.issues).toEqual(
    expect.arrayContaining([
      expect.objectContaining({
        id: `missing-source-metadata-${road.id}`,
        severity: 'warning',
        category: 'metadata',
        objectId: road.id
      }),
      expect.objectContaining({
        id: `missing-asset-license-${asset.id}`,
        severity: 'warning',
        category: 'metadata',
        objectId: asset.id
      }),
      expect.objectContaining({
        id: `missing-asset-attribution-${asset.id}`,
        severity: 'warning',
        category: 'metadata',
        objectId: asset.id
      })
    ])
  );
});

test('traffic validation warns when runtime objects omit source metadata', () => {
  const city = new CityGenerator(cityConfig).generate();
  const traffic = createTraffic(city);
  const [marking, ...remainingMarkings] = traffic.markings;
  const invalidTraffic = {
    ...traffic,
    markings: [
      {
        ...marking,
        metadata: undefined
      },
      ...remainingMarkings
    ]
  };
  const validation = validateTraffic(city, invalidTraffic);

  expect(validation.passed).toBe(true);
  expect(validation.issues).toEqual(
    expect.arrayContaining([
      expect.objectContaining({
        id: `missing-source-metadata-${marking.id}`,
        severity: 'warning',
        category: 'metadata',
        objectId: marking.id
      })
    ])
  );
});

function createTraffic(city: ReturnType<CityGenerator['generate']>) {
  return new TrafficLaneGenerator().create({
    roads: city.roads,
    crossings: city.crossings,
    intersections: city.intersections
  });
}

function validateTraffic(city: ReturnType<CityGenerator['generate']>, traffic: ReturnType<typeof createTraffic>) {
  return validateTrafficPlan({
    roads: city.roads,
    crossings: city.crossings,
    intersections: city.intersections,
    assetBindings: city.assetBindings,
    traffic
  });
}
