import type { CityObjectBase, SourceMetadata, ValidationIssue } from './cityContracts';

export const GENERATED_SOURCE_AUTHOR = 'detailed-city-generator';
export const SIMULATED_SOURCE_AUTHOR = 'detailed-city-simulation';
export const INTERNAL_PROCEDURAL_LICENSE = 'internal-procedural';
export const INTERNAL_SIMULATION_LICENSE = 'internal-simulation';
export const SOURCE_METADATA_VERSION = 'source-metadata-v1';

export function createAuthoredSourceMetadata(input: {
  readonly sourceId: string;
  readonly author: string;
  readonly license: string;
  readonly attribution?: string;
}): SourceMetadata {
  return {
    sourceType: 'authored',
    sourceId: input.sourceId,
    confidence: 1,
    author: input.author,
    license: input.license,
    attribution: input.attribution,
    reviewStatus: 'draft',
    sourceVersion: SOURCE_METADATA_VERSION
  };
}

export function createImportedSourceMetadata(input: {
  readonly sourceId: string;
  readonly attribution: string;
  readonly license: string;
  readonly confidence?: number;
}): SourceMetadata {
  return {
    sourceType: 'imported',
    sourceId: input.sourceId,
    confidence: input.confidence ?? 0.85,
    license: input.license,
    attribution: input.attribution,
    reviewStatus: 'external-unverified',
    sourceVersion: SOURCE_METADATA_VERSION
  };
}

export function createProceduralSourceMetadata(sourceId: string, generationStep: string): SourceMetadata {
  return {
    sourceType: 'procedural',
    sourceId,
    confidence: 1,
    author: GENERATED_SOURCE_AUTHOR,
    license: INTERNAL_PROCEDURAL_LICENSE,
    attribution: 'Generated by the detailed-city procedural pipeline.',
    reviewStatus: 'generated',
    generationStep,
    sourceVersion: SOURCE_METADATA_VERSION
  };
}

export function createSimulatedSourceMetadata(sourceId: string, generationStep: string): SourceMetadata {
  return {
    sourceType: 'simulated',
    sourceId,
    confidence: 1,
    author: SIMULATED_SOURCE_AUTHOR,
    license: INTERNAL_SIMULATION_LICENSE,
    attribution: 'Generated by the detailed-city deterministic simulation seed.',
    reviewStatus: 'generated',
    generationStep,
    sourceVersion: SOURCE_METADATA_VERSION
  };
}

export interface SourceMetadataValidationOptions {
  readonly requireLicense?: boolean;
  readonly requireReviewStatus?: boolean;
  readonly requireGenerationStep?: boolean;
}

export function validateSourceMetadata(
  object: CityObjectBase,
  options: SourceMetadataValidationOptions = {}
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const metadata = object.metadata;

  if (!metadata) {
    return [
      {
        id: `missing-source-metadata-${object.id}`,
        severity: 'warning',
        category: 'metadata',
        objectId: object.id,
        message: `City object ${object.id} should declare source metadata.`
      }
    ];
  }

  if (!isValidConfidence(metadata.confidence)) {
    issues.push({
      id: `invalid-source-confidence-${object.id}`,
      severity: 'warning',
      category: 'metadata',
      objectId: object.id,
      message: `City object ${object.id} source metadata confidence must be between 0 and 1.`
    });
  }

  if (!metadata.sourceId) {
    issues.push({
      id: `missing-source-id-${object.id}`,
      severity: 'warning',
      category: 'metadata',
      objectId: object.id,
      message: `City object ${object.id} source metadata should include a stable sourceId.`
    });
  }

  if ((options.requireReviewStatus ?? true) && !metadata.reviewStatus) {
    issues.push({
      id: `missing-source-review-status-${object.id}`,
      severity: 'warning',
      category: 'metadata',
      objectId: object.id,
      message: `City object ${object.id} source metadata should include a review status.`
    });
  }

  if ((options.requireLicense ?? false) && !metadata.license) {
    issues.push({
      id: `missing-source-license-${object.id}`,
      severity: 'warning',
      category: 'metadata',
      objectId: object.id,
      message: `City object ${object.id} source metadata should include license information.`
    });
  }

  if ((options.requireGenerationStep ?? isGeneratedMetadata(metadata)) && !metadata.generationStep) {
    issues.push({
      id: `missing-generation-step-${object.id}`,
      severity: 'warning',
      category: 'metadata',
      objectId: object.id,
      message: `City object ${object.id} source metadata should include the generation step.`
    });
  }

  return issues;
}

function isGeneratedMetadata(metadata: SourceMetadata): boolean {
  return metadata.sourceType === 'procedural' || metadata.sourceType === 'simulated';
}

function isValidConfidence(confidence: number): boolean {
  return Number.isFinite(confidence) && confidence >= 0 && confidence <= 1;
}
